declare const _exports: {
    HasRichPresence: number;
    InJoinableGame: number;
    Golden: number;
    RemotePlayTogether: number;
    OnlineUsingWeb: number;
    ClientTypeWeb: number;
    OnlineUsingMobile: number;
    ClientTypeMobile: number;
    OnlineUsingBigPicture: number;
    ClientTypeTenfoot: number;
    OnlineUsingVR: number;
    ClientTypeVR: number;
    LaunchTypeGamepad: number;
    LaunchTypeCompatTool: number;
    "1": string;
    "2": string;
    "4": string;
    "8": string;
    "256": string;
    "512": string;
    "1024": string;
    "2048": string;
    "4096": string;
    "8192": string;
};
export = _exports;
export type exports = any;
